"""empty message

Revision ID: 061920ecd831
Revises: 
Create Date: 2022-11-22 15:37:57.157495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061920ecd831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('lengthInMinutes', sa.Integer(), nullable=True),
    sa.Column('stepsTaken', sa.Integer(), nullable=True),
    sa.Column('pushUps', sa.Integer(), nullable=True),
    sa.Column('pullUps', sa.Integer(), nullable=True),
    sa.Column('otherExercises', sa.String(length=1000), nullable=True),
    sa.Column('bodyWeightInKG', sa.Integer(), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('user')
    # ### end Alembic commands ###
